name: Upload dummy contract workbooks to ADLS

on:
  workflow_dispatch:
  push:
    paths:
      - extracts/github_workbooks/**
      - extracts/sharepoint_workbooks/**

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: Show repo extract folders
        run: |
          pwd
          ls -la
          ls -la extracts || true
          ls -la extracts/contracts || true
          find extracts -maxdepth 4 -type f -name "*.xlsx" -print || true
      
      - name: Upload GitHub (LTI-like) workbooks
        run: |
          LOAD_DATE=$(date +%F)
          az storage blob upload-batch \
            --account-name pvcstor \
            --destination "landing/github/entity=workbook/load_date=${LOAD_DATE}" \
            --source "extracts/github_workbooks" \
            --auth-mode login
      
      - name: Upload SharePoint (historic) workbooks
        run: |
          LOAD_DATE=$(date +%F)
          az storage blob upload-batch \
            --account-name pvcstor \
            --destination "landing/sharepoint/entity=workbook/load_date=${LOAD_DATE}" \
            --source "extracts/sharepoint_workbooks" \
            --auth-mode login
